# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.test-cql
canonical: https://interop.esante.gouv.fr/ig/fhir/test-cql # the last part of canonical and id must be the same
name: TestCQL # Should be an acronym
title: POC CQL - ROR
description: Proof of concept d'utilisation de CQL (Clinical Quality Language) appliqué aux données du ROR (Répertoire de l'Offre et des Ressources en santé).
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis. Cf. https://interop.esante.gouv.fr/ig/documentation/mod_bonnes_pratiques.html#release-dun-ig-fhir colonne "label de publication"

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - tx #tx: Messages describing the use of the terminology server (for debugging)
      - html #html: Log when validating an html page (troubleshooting only - leave off)
      - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
      - init #init: Messages describing the start up process (for debugging)
      - progress #progress: Overall progress messages
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en


pages:
    index.md:
        title: Accueil
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
