services:
  hapi-fhir:
    image: hapiproject/hapi:v7.2.0
    ports:
      - "8080:8080"
    volumes:
      - ./hapi.application.yml:/app/config/application.yaml
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
