services:
  hapi-fhir:
    image: hapiproject/hapi:v8.10.0-2
    ports:
      - "8080:8080"
    volumes:
      - ./hapi.application.yml:/app/config/application.yaml
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
